import type { NodeDefinition, CategoryMeta } from "./types";

/* ──────────────────────────────────────────────────────────────────
   Node definitions — DNG Builder node labels.
   Categories: input, ai, tools, integrations, constants, output.
   ────────────────────────────────────────────────────────────────── */

export const NODE_DEFINITIONS: Record<string, NodeDefinition> = {
  // ── Inputs ──────────────────────────────────────────────────────
  Text: {
    label: "Text",
    category: "input",
    type: "Input",
    description: "Long text input (paragraph)",
    inputs: [],
    outputs: [{ id: "output_0", label: "Text", type: "string" }],
    params: [
      { name: "defaultValue", label: "Default value", type: "textarea" },
    ],
  },
  "Short Text": {
    label: "Short Text",
    category: "input",
    type: "Input",
    description: "Single-line text input",
    inputs: [],
    outputs: [{ id: "output_0", label: "Text", type: "string" }],
    params: [
      { name: "defaultValue", label: "Default value", type: "text" },
    ],
  },
  Url: {
    label: "Url",
    category: "input",
    type: "Input",
    description: "URL input",
    inputs: [],
    outputs: [{ id: "output_0", label: "URL", type: "string" }],
    params: [
      { name: "defaultValue", label: "Default URL", type: "text" },
    ],
  },
  File: {
    label: "File",
    category: "input",
    type: "Input",
    description: "File input (PDF, CSV, TXT, …)",
    inputs: [],
    outputs: [{ id: "output_0", label: "Content", type: "string" }],
    params: [
      { name: "type", label: "File type", type: "select", options: ["PDF", "CSV", "TXT", "JSON", "DOCX"] },
    ],
  },
  Date: {
    label: "Date",
    category: "input",
    type: "Input",
    description: "Date input",
    inputs: [],
    outputs: [{ id: "output_0", label: "Date", type: "string" }],
    params: [
      { name: "defaultValue", label: "Default date", type: "text" },
    ],
  },
  Select: {
    label: "Select",
    category: "input",
    type: "Input",
    description: "Dropdown list of options",
    inputs: [],
    outputs: [{ id: "output_0", label: "Selection", type: "string" }],
    params: [
      { name: "options", label: "Options (one per line)", type: "textarea" },
    ],
  },

  // ── AI ──────────────────────────────────────────────────────────
  LLM: {
    label: "LLM",
    category: "ai",
    type: "AI",
    description: "Language model (GPT, Claude, …)",
    inputs: [{ id: "input_0", label: "Input", type: "string" }],
    outputs: [{ id: "output_0", label: "Response", type: "string" }],
    params: [
      { name: "modelName", label: "Model", type: "select", options: ["gpt-4o", "gpt-4", "gpt-4-turbo", "gpt-3.5-turbo", "claude-3.5-sonnet", "claude-3-opus", "claude-3-sonnet", "claude-3-haiku", "gemini-1.5-pro", "gemini-1.5-flash", "mistral-large"] },
      { name: "temperature", label: "Temperature", type: "number", default: 0.7 },
      { name: "maxOutputTokens", label: "Max tokens", type: "number", default: 2000 },
      { name: "systemMessage", label: "System message", type: "textarea" },
      { name: "prompt", label: "Prompt", type: "textarea" },
    ],
  },
  Agent: {
    label: "Agent",
    category: "ai",
    type: "AI",
    description: "Autonomous AI agent with tools",
    inputs: [{ id: "input_0", label: "Instructions", type: "string" }],
    outputs: [{ id: "output_0", label: "Result", type: "string" }],
    params: [
      { name: "modelName", label: "Model", type: "select", options: ["gpt-4o", "gpt-4", "claude-3.5-sonnet", "claude-3-opus", "gemini-1.5-pro"] },
      { name: "temperature", label: "Temperature", type: "number", default: 0.5 },
      { name: "maxOutputTokens", label: "Max tokens", type: "number", default: 4000 },
      { name: "agentSystemMessage", label: "System message", type: "textarea" },
      { name: "agentTools", label: "Tools", type: "select", options: ["web_search", "code_execution", "file_read", "calculator"] },
      { name: "prompt", label: "Prompt", type: "textarea" },
    ],
  },
  "AI Code": {
    label: "AI Code",
    category: "ai",
    type: "AI",
    description: "AI code generation",
    inputs: [
      { id: "input_data_1", label: "Data 1", type: "string" },
      { id: "input_data_2", label: "Data 2", type: "string" },
    ],
    outputs: [{ id: "output_0", label: "Code", type: "string" }],
    params: [
      { name: "modelName", label: "Model", type: "select", options: ["gpt-4o", "gpt-4", "claude-3.5-sonnet"] },
      { name: "prompt", label: "Prompt", type: "textarea" },
    ],
  },
  "Text to Image": {
    label: "Text to Image",
    category: "ai",
    type: "AI",
    description: "Generate an image from text",
    inputs: [{ id: "input_0", label: "Description", type: "string" }],
    outputs: [{ id: "output_0", label: "Image", type: "string" }],
    params: [
      { name: "modelName", label: "Model", type: "select", options: ["dall-e-3", "dall-e-2", "stable-diffusion-xl", "midjourney"] },
      { name: "size", label: "Size", type: "select", options: ["1024x1024", "1792x1024", "1024x1792", "512x512"] },
      { name: "quality", label: "Quality", type: "select", options: ["standard", "hd"] },
      { name: "prompt", label: "Image prompt", type: "textarea" },
    ],
  },
  "Image to Text": {
    label: "Image to Text",
    category: "ai",
    type: "AI",
    description: "Extract text from an image",
    inputs: [{ id: "input_0", label: "Image", type: "string" }],
    outputs: [{ id: "output_0", label: "Text", type: "string" }],
    params: [
      { name: "modelName", label: "Model", type: "select", options: ["gpt-4o", "claude-3.5-sonnet", "gemini-1.5-pro"] },
      { name: "prompt", label: "Instructions", type: "textarea" },
    ],
  },

  // ── Tools ───────────────────────────────────────────────────────
  "Web Scraper": {
    label: "Web Scraper",
    category: "tools",
    type: "Tool",
    description: "Fetch and extract web content",
    inputs: [{ id: "url", label: "URL", type: "string" }],
    outputs: [{ id: "html", label: "HTML", type: "string" }],
    params: [
      { name: "contentType", label: "Content type", type: "select", options: ["Article", "ArticleList", "Product", "ProductList", "No Template"] },
      { name: "xPath_1", label: "XPath 1 (optional)", type: "text" },
      { name: "errorHandling", label: "Error handling", type: "select", options: ["None", "Skip"] },
    ],
  },
  "HTML to Markdown": {
    label: "HTML to Markdown",
    category: "tools",
    type: "Tool",
    description: "Convert HTML to readable Markdown",
    inputs: [{ id: "input_0", label: "HTML", type: "string" }],
    outputs: [{ id: "output_0", label: "Markdown", type: "string" }],
    params: [],
  },
  "HTML Cleaner": {
    label: "HTML Cleaner",
    category: "tools",
    type: "Tool",
    description: "Strip scripts, styles, and noise from HTML",
    inputs: [{ id: "input_0", label: "HTML", type: "string" }],
    outputs: [{ id: "output_0", label: "Clean HTML", type: "string" }],
    params: [],
  },
  "CSV Analyzer": {
    label: "CSV Analyzer",
    category: "tools",
    type: "Tool",
    description: "Analyze a CSV file",
    inputs: [{ id: "input_0", label: "CSV", type: "string" }],
    outputs: [{ id: "output_0", label: "Analysis", type: "string" }],
    params: [
      { name: "analysisType", label: "Analysis type", type: "select", options: ["summary", "statistics", "preview"] },
    ],
  },
  "Conditional Node": {
    label: "Conditional Node",
    category: "tools",
    type: "Tool",
    description: "Conditional branching (IF / ELSE)",
    inputs: [{ id: "input_0", label: "Input", type: "string" }],
    outputs: [
      { id: "output_true", label: "IF (true)", type: "string" },
      { id: "output_false", label: "ELSE (false)", type: "string" },
    ],
    params: [
      { name: "variable", label: "Variable to test", type: "text" },
      { name: "operator", label: "Operator", type: "select", options: ["contains", "not_contains", "equals", "not_equals", "starts_with", "ends_with", "greater_than", "less_than", "is_empty", "is_not_empty"] },
      { name: "value", label: "Compare value", type: "text" },
    ],
  },
  "Loop Node": {
    label: "Loop Node",
    category: "tools",
    type: "Tool",
    description: "Iterate over a list",
    inputs: [{ id: "list", label: "List", type: "json" }],
    outputs: [
      { id: "loop", label: "Iteration", type: "json" },
      { id: "done", label: "Done", type: "json" },
    ],
    params: [
      { name: "maxIterations", label: "Max iterations", type: "number", default: 10 },
      { name: "delayBetweenIterations", label: "Delay between iterations (ms)", type: "number", default: 100 },
      { name: "errorHandling", label: "Error handling", type: "select", options: ["None", "Skip"] },
    ],
  },
  "HTTP Request": {
    label: "HTTP Request",
    category: "tools",
    type: "Tool",
    description: "HTTP call (API, webhook, …)",
    inputs: [{ id: "input_0", label: "Data", type: "string" }],
    outputs: [{ id: "output_0", label: "Response", type: "string" }],
    params: [
      { name: "url", label: "URL", type: "text" },
      { name: "method", label: "Method", type: "select", options: ["GET", "POST", "PUT", "PATCH", "DELETE"] },
      { name: "headers", label: "Headers (JSON)", type: "textarea" },
      { name: "body", label: "Body", type: "textarea" },
    ],
  },
  "Merge With Template": {
    label: "Merge With Template",
    category: "tools",
    type: "Tool",
    description: "Merge data into a template with {{variable}}",
    inputs: [{ id: "input_0", label: "Data", type: "string" }],
    outputs: [{ id: "content", label: "Content", type: "string" }],
    params: [
      { name: "template", label: "Template", type: "textarea" },
    ],
  },
  "JSON Path Extractor": {
    label: "JSON Path Extractor",
    category: "tools",
    type: "Tool",
    description: "Extract values from JSON with JSONPath",
    inputs: [{ id: "input_0", label: "JSON", type: "string" }],
    outputs: [{ id: "output_0", label: "Value", type: "string" }],
    params: [
      { name: "path", label: "JSONPath", type: "text" },
    ],
  },
  "Find And Replace": {
    label: "Find And Replace",
    category: "tools",
    type: "Tool",
    description: "Find and replace in text",
    inputs: [{ id: "input_0", label: "Text", type: "string" }],
    outputs: [{ id: "output_0", label: "Result", type: "string" }],
    params: [
      { name: "find", label: "Find", type: "text" },
      { name: "replace", label: "Replace with", type: "text" },
      { name: "useRegex", label: "Regex", type: "select", options: ["false", "true"] },
    ],
  },
  Split: {
    label: "Split",
    category: "tools",
    type: "Tool",
    description: "Split text into parts",
    inputs: [{ id: "text", label: "Text", type: "string" }],
    outputs: [{ id: "splitted_text", label: "Parts", type: "string" }],
    params: [],
  },
  "Diff Checker": {
    label: "Diff Checker",
    category: "tools",
    type: "Tool",
    description: "Compare two texts and show differences",
    inputs: [
      { id: "input_0", label: "Text A", type: "string" },
      { id: "input_1", label: "Text B", type: "string" },
    ],
    outputs: [{ id: "output_0", label: "Diff", type: "string" }],
    params: [],
  },
  "Word Counter": {
    label: "Word Counter",
    category: "tools",
    type: "Tool",
    description: "Count words and characters",
    inputs: [{ id: "input_0", label: "Text", type: "string" }],
    outputs: [{ id: "output_0", label: "Count", type: "string" }],
    params: [],
  },
  "Tag Extractor": {
    label: "Tag Extractor",
    category: "tools",
    type: "Tool",
    description: "Extract specific HTML tags",
    inputs: [{ id: "input_0", label: "HTML", type: "string" }],
    outputs: [{ id: "output_0", label: "Tags", type: "string" }],
    params: [
      { name: "tagName", label: "Tag (h1, a, img, …)", type: "text" },
    ],
  },
  "Human_in_the_Loop": {
    label: "Human_in_the_Loop",
    category: "tools",
    type: "Tool",
    description: "Human validation checkpoint",
    inputs: [{ id: "input_0", label: "Data", type: "string" }],
    outputs: [{ id: "output_0", label: "Approved", type: "string" }],
    params: [
      { name: "instructions", label: "Instructions for the reviewer", type: "textarea" },
    ],
  },
  "Fail Node": {
    label: "Fail Node",
    category: "tools",
    type: "Tool",
    description: "Stop the workflow with an error",
    inputs: [{ id: "input_0", label: "Input", type: "string" }],
    outputs: [],
    params: [
      { name: "errorMessage", label: "Error message", type: "text" },
    ],
  },
  "Create_List": {
    label: "Create_List",
    category: "tools",
    type: "Tool",
    description: "Build a list from items",
    inputs: [{ id: "input_0", label: "Item", type: "string" }],
    outputs: [{ id: "output_0", label: "List", type: "json" }],
    params: [],
  },
  "Join_List": {
    label: "Join_List",
    category: "tools",
    type: "Tool",
    description: "Join list items into text",
    inputs: [{ id: "input_0", label: "List", type: "json" }],
    outputs: [{ id: "output_0", label: "Text", type: "string" }],
    params: [
      { name: "separator", label: "Separator", type: "text" },
    ],
  },
  "Merge_Lists": {
    label: "Merge_Lists",
    category: "tools",
    type: "Tool",
    description: "Merge multiple lists",
    inputs: [
      { id: "list_0", label: "List 1", type: "json" },
      { id: "list_1", label: "List 2", type: "json" },
    ],
    outputs: [{ id: "merged_list", label: "Merged list", type: "json" }],
    params: [],
  },
  "Filter_List": {
    label: "Filter_List",
    category: "tools",
    type: "Tool",
    description: "Filter a list by a condition",
    inputs: [{ id: "input_0", label: "List", type: "json" }],
    outputs: [{ id: "output_0", label: "Filtered list", type: "json" }],
    params: [
      { name: "condition", label: "Filter condition", type: "text" },
    ],
  },
  "Pick_List_Item": {
    label: "Pick_List_Item",
    category: "tools",
    type: "Tool",
    description: "Pick an element by index",
    inputs: [{ id: "input_0", label: "List", type: "json" }],
    outputs: [{ id: "output_0", label: "Item", type: "string" }],
    params: [
      { name: "index", label: "Index", type: "number", default: 0 },
    ],
  },

  // ── Integrations ────────────────────────────────────────────────
  "Email Sender": {
    label: "Email Sender",
    category: "integrations",
    type: "Tool",
    description: "Send an email",
    inputs: [{ id: "input_0", label: "Content", type: "string" }],
    outputs: [{ id: "output_0", label: "Status", type: "string" }],
    params: [
      { name: "to", label: "To", type: "text" },
      { name: "subject", label: "Subject", type: "text" },
      { name: "body", label: "Body", type: "textarea" },
    ],
  },
  "Serper Dev": {
    label: "Serper Dev",
    category: "integrations",
    type: "Tool",
    description: "Web search via Serper (SERP API)",
    inputs: [{ id: "input_0", label: "Query", type: "string" }],
    outputs: [{ id: "output_0", label: "Results", type: "string" }],
    params: [
      { name: "query", label: "Search query", type: "text" },
      { name: "numResults", label: "Number of results", type: "number", default: 10 },
      { name: "searchType", label: "Type", type: "select", options: ["search", "news", "images"] },
    ],
  },
  "Google Search Console": {
    label: "Google Search Console",
    category: "integrations",
    type: "Tool",
    description: "Search Console data (queries, pages, …)",
    inputs: [{ id: "input_0", label: "Params", type: "string" }],
    outputs: [{ id: "output_0", label: "Data", type: "string" }],
    params: [
      { name: "siteUrl", label: "Site URL", type: "text" },
      { name: "dateRange", label: "Date range", type: "select", options: ["7d", "28d", "3m", "6m", "12m"] },
      { name: "dimension", label: "Dimension", type: "select", options: ["query", "page", "country", "device"] },
    ],
  },
  "Google Sheets": {
    label: "Google Sheets",
    category: "integrations",
    type: "Tool",
    description: "Write to Google Sheets",
    inputs: [{ id: "input_0", label: "Data", type: "string" }],
    outputs: [{ id: "output_0", label: "Status", type: "string" }],
    params: [
      { name: "spreadsheetId", label: "Spreadsheet ID", type: "text" },
      { name: "sheetName", label: "Sheet name", type: "text" },
      { name: "writeMode", label: "Write mode", type: "select", options: ["append", "overwrite"] },
    ],
  },
  "Google Sheets Reader": {
    label: "Google Sheets Reader",
    category: "integrations",
    type: "Tool",
    description: "Read from Google Sheets",
    inputs: [],
    outputs: [{ id: "output_0", label: "Data", type: "string" }],
    params: [
      { name: "spreadsheetId", label: "Spreadsheet ID", type: "text" },
      { name: "sheetName", label: "Sheet name", type: "text" },
      { name: "range", label: "Range (e.g. A1:D50)", type: "text" },
    ],
  },
  "WordPress Post Create": {
    label: "WordPress Post Create",
    category: "integrations",
    type: "Tool",
    description: "Publish a WordPress post",
    inputs: [{ id: "input_0", label: "Content", type: "string" }],
    outputs: [{ id: "output_0", label: "Post ID", type: "string" }],
    params: [
      { name: "status", label: "Status", type: "select", options: ["draft", "publish", "pending"] },
      { name: "category", label: "Category", type: "text" },
      { name: "tags", label: "Tags (comma-separated)", type: "text" },
    ],
  },
  "Google_Docs_Writer": {
    label: "Google_Docs_Writer",
    category: "integrations",
    type: "Tool",
    description: "Write to Google Docs",
    inputs: [{ id: "input_0", label: "Content", type: "string" }],
    outputs: [{ id: "output_0", label: "Link", type: "string" }],
    params: [
      { name: "documentTitle", label: "Document title", type: "text" },
    ],
  },

  // ── Constants ───────────────────────────────────────────────────
  "Static_Text": {
    label: "Static_Text",
    category: "constants",
    type: "Constant",
    description: "Static text (fixed value)",
    inputs: [],
    outputs: [{ id: "output_0", label: "Text", type: "string" }],
    params: [
      { name: "value", label: "Value", type: "textarea" },
    ],
  },

  // ── Output ──────────────────────────────────────────────────────
  Output: {
    label: "Output",
    category: "output",
    type: "Output",
    description: "Workflow output",
    inputs: [{ id: "input_0", label: "Result", type: "string" }],
    outputs: [],
    params: [
      { name: "outputName", label: "Output name", type: "text" },
    ],
  },
};

export const CATEGORY_META: Record<string, CategoryMeta> = {
  input: {
    label: "Inputs",
    color: "#10b981",
    bgClass: "bg-emerald-500/10",
    borderClass: "border-emerald-500/40",
    headerClass: "bg-emerald-600",
  },
  ai: {
    label: "AI",
    color: "#8b5cf6",
    bgClass: "bg-violet-500/10",
    borderClass: "border-violet-500/40",
    headerClass: "bg-violet-600",
  },
  tools: {
    label: "Tools",
    color: "#f59e0b",
    bgClass: "bg-amber-500/10",
    borderClass: "border-amber-500/40",
    headerClass: "bg-amber-600",
  },
  integrations: {
    label: "Integrations",
    color: "#06b6d4",
    bgClass: "bg-cyan-500/10",
    borderClass: "border-cyan-500/40",
    headerClass: "bg-cyan-600",
  },
  constants: {
    label: "Constants",
    color: "#71717a",
    bgClass: "bg-zinc-500/10",
    borderClass: "border-zinc-500/40",
    headerClass: "bg-zinc-600",
  },
  output: {
    label: "Outputs",
    color: "#f43f5e",
    bgClass: "bg-rose-500/10",
    borderClass: "border-rose-500/40",
    headerClass: "bg-rose-600",
  },
};
