#!/usr/bin/env python3
"""
Export English challenge JSON for the DNG exam.

Writes the FULL challenges (with ideal_workflow / grading_rubric / exam_blueprint)
into `n8n/server-challenges/` — the server-only source of truth. The candidate-facing
sanitized copies in `n8n/nodes-dng/challenges/` are then regenerated by
`n8n/nodes-dng/scripts/sanitize-challenges.mjs` (run automatically by `npm run build`).

Requires: a copy of the legacy `app/challenges_data.py` module on PYTHONPATH.
(If this repo has no `backend/`, use `git worktree` or a branch that still
contains it, or only edit the committed JSON in `n8n/server-challenges/`.)
Run: cd <repo> && poetry -C backend run python n8n/nodes-dng/scripts/extract-challenges.py
(Install dev dependency: poetry -C backend add --group dev deep-translator)
"""
from __future__ import annotations

import importlib.util
import json
import os
import re
import sys
from copy import deepcopy
from typing import Any

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
BACKEND = os.path.join(ROOT, "backend")
OUT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "server-challenges"))


def load_challenges():
    spec = importlib.util.spec_from_file_location(
        "challenges_data", os.path.join(BACKEND, "app", "challenges_data.py")
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore
    return mod.CHALLENGES


def map_difficulty(d: str) -> str:
    return {
        "Facile": "Easy",
        "Intermédiaire": "Intermediate",
        "Avancé": "Advanced",
        "Expert": "Expert",
    }.get(d, d)


def map_category(c: str) -> str:
    return {
        "Fondamentaux": "Fundamentals",
        "Extraction de données": "Data extraction",
        "Logique de flux": "Flow logic",
        "Data & Analyse": "Data & analytics",
        "Recherche & SERP": "Search & SERP",
        "Agents IA": "AI agents",
        "Automatisation": "Automation",
        "Contenu & Publication": "Content & publishing",
        "Qualité & Revue": "Quality & review",
        "SEO & Performance": "SEO & performance",
    }.get(c, c)


def has_latin1_french(s: str) -> bool:
    if not s or not isinstance(s, str):
        return False
    if re.search(r"[éèêëàâäùûüôöîïçÉÈÀÇ]", s):
        return True
    # common French words in our prompts
    if re.search(
        r"\b(le|la|les|un|une|des|et|est|vous|nous|pour|dans|avec|sont|cette|ce|qui)\b",
        s,
        re.I,
    ) and len(s) > 30:
        return True
    return False


def get_translator():
    try:
        from deep_translator import GoogleTranslator  # type: ignore

        return GoogleTranslator(source="fr", target="en")
    except Exception:
        return None


_CACHE: dict[str, str] = {}


def translate_str(tr, s: str) -> str:
    if s in _CACHE:
        return _CACHE[s]
    if not tr or not has_latin1_french(s):
        return s
    if len(s) > 15000:
        return s
    try:
        out = tr.translate(s)
        _CACHE[s] = out
        return out
    except Exception:
        return s


def walk_translate(obj: Any, tr) -> Any:
    if isinstance(obj, dict):
        return {k: walk_translate(v, tr) for k, v in obj.items()}
    if isinstance(obj, list):
        return [walk_translate(x, tr) for x in obj]
    if isinstance(obj, str):
        return translate_str(tr, obj)
    return obj


def to_public_challenge(raw: dict, tr) -> dict:
    en = (raw.get("translations") or {}).get("en") or {}
    title = en.get("title") or raw.get("title", "")
    desc = en.get("description") or raw.get("description", "")
    c = {
        "id": raw["id"],
        "title": title,
        "description": desc,
        "difficulty": map_difficulty(raw.get("difficulty", "")),
        "category": map_category(raw.get("category", "")),
        "time_limit_minutes": raw.get("time_limit_minutes"),
        "available_nodes": raw.get("available_nodes", []),
        "exam_blueprint": deepcopy(raw.get("exam_blueprint", [])),
        "grading_rubric": deepcopy(raw.get("grading_rubric", {})),
        "ideal_workflow": walk_translate(deepcopy(raw.get("ideal_workflow", {})), tr),
    }
    return c


def main() -> int:
    if not os.path.isdir(BACKEND):
        print(
            "No backend/ directory — cannot import challenges_data. "
            "The committed files in n8n/server-challenges/ are the source of truth.",
            file=sys.stderr,
        )
        return 1
    os.makedirs(OUT_DIR, exist_ok=True)
    CHALLENGES = load_challenges()
    tr = get_translator()
    if tr is None:
        print("Warning: deep_translator not installed; install with: pip install deep-translator", file=sys.stderr)
        print("         Exporting; ideal_workflow long strings may stay French.", file=sys.stderr)
    index = []
    for raw in CHALLENGES:
        c = to_public_challenge(raw, tr)
        path = os.path.join(OUT_DIR, f"{c['id']}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(c, f, ensure_ascii=False, indent=2)
        index.append(
            {
                "id": c["id"],
                "title": c["title"],
                "difficulty": c["difficulty"],
                "category": c["category"],
                "time_limit_minutes": c.get("time_limit_minutes"),
            }
        )
    with open(os.path.join(OUT_DIR, "index.json"), "w", encoding="utf-8") as f:
        json.dump(index, f, ensure_ascii=False, indent=2)
    print(f"Wrote {len(index)} challenges to {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
